In [136]:
#数据清洁
import pandas as pd

badge_batch1 = pd.read_excel("../data/raw/徽章一批.xlsx")
badge_batch2 = pd.read_excel("../data/raw/徽章二批.xlsx")
baseball = pd.read_excel("../data/raw/棒球服.xlsx")
badge_extra = pd.read_excel("../data/raw/徽章余量.xlsx")

In [137]:
print("徽章一批：", badge_batch1.columns.tolist())
print("徽章二批：", badge_batch2.columns.tolist())
print("棒球服：", baseball.columns.tolist())
print("徽章余量：", badge_extra.columns.tolist())

徽章一批： ['发货时间', '订单编号（勿删）', '商品ID（勿删）', '单价', '订单状态', '退款状态', '支付时间', '商品名称', '商品型号', '销售批次', '商品件数', '邮费']
徽章二批： ['发货时间', '订单编号（勿删）', '商品ID（勿删）', '单价', '订单状态', '退款状态', '支付时间', '商品名称', '商品型号', '销售批次', '商品件数', '邮费']
棒球服： ['发货时间', '订单编号（勿删）', '商品ID（勿删）', '单价', '订单状态', '退款状态', '支付时间', '商品名称', '商品型号', '销售批次', '商品件数', '邮费']
徽章余量： ['发货时间', '订单编号（勿删）', '商品ID（勿删）', '单价', '订单状态', '退款状态', '支付时间', '商品名称', '商品型号', '销售批次', '商品件数', '邮费']

In [138]:
orders = pd.concat(
    [badge_batch1, badge_batch2, baseball, badge_extra],
    ignore_index=True
)

In [139]:
orders.shape

(312, 12)

In [140]:
orders.head()

,发货时间,订单编号（勿删）,商品ID（勿删）,单价,订单状态,退款状态,支付时间,商品名称,商品型号,销售批次,商品件数,邮费
0,2024.12.3,100001,7300251109,23.6,已完成,NaN,2024-12-17 12:10:02,徽章,无,徽章一批,1,6
1,2024.12.3,100002,7300251109,23.6,已完成,NaN,2024-12-04 11:39:25,徽章,无,徽章一批,1,6
2,2024.12.3,100003,7300251109,23.6,已完成,NaN,2024-12-04 00:29:16,徽章,无,徽章一批,1,6
3,2024.12.3,100004,7300251109,23.6,已完成,NaN,2024-12-07 17:30:34,徽章,无,徽章一批,1,6
4,2024.12.3,100005,7300251109,23.6,已完成,NaN,2024-12-03 11:49:04,徽章,无,徽章一批,1,6

In [141]:
orders.to_excel("../data/processed/orders_clean.xlsx", index=False)

In [142]:
# 转换发货时间为日期类型
orders["发货时间"] = pd.to_datetime(orders["发货时间"],errors="coerce")

# 转换支付时间为日期类型
orders["支付时间"] = pd.to_datetime(orders["支付时间"])

# 订单编号转换为字符串
orders["订单编号（勿删）"] = orders["订单编号（勿删）"].astype(str)

In [143]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 312 entries, 0 to 311
Data columns (total 12 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   发货时间      311 non-null    datetime64[ns]
 1   订单编号（勿删）  312 non-null    object
 2   商品ID（勿删）  312 non-null    int64
 3   单价        312 non-null    float64
 4   订单状态      312 non-null    object
 5   退款状态      3 non-null      object
 6   支付时间      312 non-null    datetime64[ns]
 7   商品名称      312 non-null    object
 8   商品型号      312 non-null    object
 9   销售批次      312 non-null    object
 10  商品件数      312 non-null    int64
 11  邮费        312 non-null    int64
dtypes: datetime64[ns](2), float64(1), int64(3), object(6)
memory usage: 29.4+ KB

In [144]:
orders[orders["发货时间"].isnull()]

,发货时间,订单编号（勿删）,商品ID（勿删）,单价,订单状态,退款状态,支付时间,商品名称,商品型号,销售批次,商品件数,邮费
183,NaT,100184,7347068888,23.6,退款成功,退款完成(全额退款),2025-01-05 20:10:06,徽章,无,徽章二批,1,6

In [145]:
orders.isnull().sum()

发货时间          1
订单编号（勿删）      0
商品ID（勿删）      0
单价            0
订单状态          0
退款状态        309
支付时间          0
商品名称          0
商品型号          0
销售批次          0
商品件数          0
邮费            0
dtype: int64

In [146]:
orders.duplicated().sum()

0

In [147]:
orders.describe()

           商品ID（勿删）          单价        商品件数          邮费
count  3.120000e+02  312.000000  312.000000  312.000000
mean   7.331508e+09   43.087821    1.016026    6.291667
std    2.772293e+07   48.820507    0.125776    0.740336
min    7.300251e+09   23.600000    1.000000    6.000000
25%    7.300251e+09   23.600000    1.000000    6.000000
50%    7.347069e+09   23.600000    1.000000    6.000000
75%    7.347069e+09   23.600000    1.000000    6.000000
max    7.388499e+09  165.000000    2.000000   11.000000

In [148]:
orders.to_excel("../data/processed/orders_clean.xlsx",index=False)